// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type Uuid = string;

/**
 * Canonical IPv4 or IPv6 address without a prefix length.
 */
export type IpAddress = string;

export type InterfaceName = string;

export type ProviderId = 'ookla' | 'librespeed' | 'cloudflare';

export type IpFamily = 'auto' | 'ipv4' | 'ipv6';

export type ResultStatus = 'queued' | 'validating' | 'running' | 'succeeded' | 'failed' | 'skipped' | 'cancelled';

export type TriggerType = 'scheduled' | 'manual';

export type ErrorEnvelope = {
    error: {
        code: string;
        message: string;
        requestId: string;
    };
};

export type Health = {
    status: 'ok';
    version: string;
    uptimeSeconds: number;
};

export type Readiness = {
    status: 'ready';
};

export type TaskFields = {
    name: string;
    description?: string;
    enabled: boolean;
    provider: ProviderId;
    /**
     * Standard five-field cron expression. Defaults to `0 * * * *` when omitted on creation.
     */
    cronExpression?: string;
    /**
     * IANA timezone. Defaults to the persisted `settings.defaultTimezone` when omitted on creation.
     */
    timezone?: string;
    randomJitterSeconds?: number;
    serverSelectionMode?: 'automatic' | 'fixed' | 'custom';
    serverId?: string;
    serverUrl?: string;
    customServerDefinition?: {
        [key: string]: unknown;
    };
    interfaceName: InterfaceName;
    sourceIp: IpAddress;
    ipFamily?: IpFamily;
    routeProfileId?: Uuid | null;
    /**
     * Defaults to the persisted `settings.defaultTaskTimeoutSeconds` when omitted on creation.
     */
    timeoutSeconds?: number;
    providerOptions?: {
        [key: string]: unknown;
    };
    preventOverlap?: boolean;
    routeValidation?: 'required' | 'interface-only';
};

/**
 * On update, omitted defaultable fields retain their existing persisted task values.
 */
export type TaskInput = TaskFields;

export type Task = TaskFields & {
    id: Uuid;
    createdAt: string;
    updatedAt: string;
    lastScheduledAt: string | null;
    nextScheduledAt: string | null;
    networkPathValid: boolean;
    networkPathMessage: string;
};

export type NextRuns = {
    taskId: Uuid;
    cronExpression: string;
    timezone: string;
    nextRuns: [
        string,
        string,
        string,
        string,
        string
    ];
};

export type ResultFields = {
    id: Uuid;
    taskId: Uuid;
    routeProfileId: Uuid | null;
    trigger: TriggerType;
    provider: ProviderId;
    queuedAt: string;
    scheduledAt: string | null;
    startedAt: string | null;
    finishedAt: string | null;
    status: ResultStatus;
    downloadBitsPerSecond?: number | null;
    uploadBitsPerSecond?: number | null;
    latencyMilliseconds?: number | null;
    jitterMilliseconds?: number | null;
    packetLossPercent?: number | null;
    downloadBytes?: number | null;
    uploadBytes?: number | null;
    selectedInterface: InterfaceName;
    selectedSourceIp: IpAddress;
    detectedPublicIp: string;
    serverId: string;
    serverName: string;
    serverHost: string;
    serverSponsor: string;
    serverLocation: string;
    serverCountry: string;
    providerResultUrl: string;
    cloudflareColo: string;
    executionDurationMs: number;
    processExitCode?: number | null;
    sanitizedError: string;
    providerVersion: string;
    applicationVersion: string;
    /**
     * Whether TLS certificate verification was explicitly disabled for this test.
     */
    tlsVerificationDisabled: boolean;
};

/**
 * Bounded result metadata returned by collection and dashboard endpoints; large diagnostics are omitted.
 */
export type ResultSummary = ResultFields;

/**
 * Full result detail including bounded diagnostic data.
 */
export type Result = ResultFields & {
    routeValidationSnapshot: {
        [key: string]: unknown;
    };
    rawProviderResponse: string;
};

export type ResultPage = {
    items: Array<ResultSummary>;
    page: number;
    pageSize: number;
    totalItems: number;
    totalPages: number;
};

export type DashboardTaskResult = {
    taskId: Uuid;
    taskName: string;
    enabled: boolean;
    interfaceName: InterfaceName;
    sourceIp: IpAddress;
    latestResult: ResultSummary | null;
};

export type DashboardPathResult = {
    interfaceName: InterfaceName;
    sourceIp: IpAddress;
    taskIds: Array<Uuid>;
    latestResult: ResultSummary | null;
};

export type DashboardResultSummary = {
    latestByTask: Array<DashboardTaskResult>;
    latestByPath: Array<DashboardPathResult>;
    activeRuns: Array<ResultSummary>;
    recentFailures: Array<ResultSummary>;
    failedTaskCount: number;
};

export type NetworkInterface = {
    name: InterfaceName;
    index: number;
    operational: boolean;
    operationalState: string;
    loopback: boolean;
    virtual: boolean;
    macAddress: string;
    mtu: number;
    addresses: Array<InterfaceAddress>;
};

export type InterfaceAddress = {
    address: IpAddress;
    family: 'ipv4' | 'ipv6';
    linkLocal: boolean;
};

export type InterfaceSnapshot = {
    items: Array<NetworkInterface>;
    /**
     * Compatibility alias for `items` containing the same interface snapshot.
     */
    interfaces?: Array<NetworkInterface>;
    refreshedAt: string;
};

export type RouteProfileFields = {
    name: string;
    description?: string;
    interfaceName: InterfaceName;
    sourceIp: IpAddress;
    expectedGateway?: string;
    /**
     * Optional unsigned 32-bit numeric table ID or shell-safe Linux routing-table name.
     */
    expectedRoutingTable?: string;
    validationTarget?: string;
    notes?: string;
};

export type RouteProfileInput = RouteProfileFields;

export type RouteProfile = RouteProfileFields & {
    id: Uuid;
    createdAt: string;
    updatedAt: string;
    lastValidationAt: string | null;
    lastValidationSucceeded: boolean | null;
    lastValidationSnapshot: {
        [key: string]: unknown;
    };
};

export type RouteValidation = {
    success: boolean;
    interfaceName: string;
    sourceIp: string;
    gateway: string;
    routingTable: string;
    destination: string;
    detectedPublicIp: string;
    reachable: boolean;
    durationMs: number;
    validatedAt: string;
    message: string;
};

export type ProviderCapabilities = {
    serverDiscovery: boolean;
    fixedServerIds: boolean;
    customServerUrls: boolean;
    interfaceBinding: boolean;
    sourceAddressBinding: boolean;
    ipv4: boolean;
    ipv6: boolean;
    jitter: boolean;
    packetLoss: boolean;
    resultUrls: boolean;
};

export type ProviderDescriptor = {
    id: ProviderId;
    displayName: string;
    capabilities: ProviderCapabilities;
    available: boolean;
    version: string;
    message: string;
};

export type OoklaBinaryStatus = {
    uploadEnabled: boolean;
    installed: boolean;
    maxUploadBytes: number;
    message: string;
};

export type OoklaBinaryInstallResult = {
    uploadEnabled: boolean;
    installed: true;
    maxUploadBytes: number;
    message: string;
    version: string;
    sha256: string;
};

export type ProviderServer = {
    id: string;
    name: string;
    host: string;
    sponsor: string;
    location: string;
    country: string;
    distanceKilometers?: number;
    url?: string;
};

export type TestTarget = {
    selectionMode: 'automatic' | 'fixed' | 'custom';
    serverId?: string;
    serverUrl?: string;
    customServerDefinition?: {
        [key: string]: unknown;
    };
};

export type ProviderServerValidation = {
    selectionMode: 'automatic' | 'fixed' | 'custom';
    serverId?: string;
    serverUrl?: string;
    customServerDefinition?: {
        [key: string]: unknown;
    };
    /**
     * Provider-specific validation options. LibreSpeed accepts the explicit `skipTlsVerification` boolean.
     */
    providerOptions?: {
        [key: string]: unknown;
    };
    interfaceName: InterfaceName;
    sourceIp: IpAddress;
    ipFamily?: IpFamily;
};

export type Settings = {
    displayUnits: 'bits' | 'bytes';
    defaultTimezone: string;
    globalConcurrency: number;
    allowSeparateWanConcurrency: boolean;
    retentionMode: 'forever' | 'days' | 'months';
    retentionValue: number;
    defaultChartRange: '24h' | '7d' | '30d' | '90d';
    interfaceRefreshIntervalSeconds: number;
    defaultTaskTimeoutSeconds: number;
    databaseMaintenanceSchedule: string;
    /**
     * Whether an operator recorded the legacy-named technical terms acknowledgement and CLI flag authorization through the dedicated endpoint.
     */
    readonly ooklaEulaAccepted?: boolean;
    /**
     * UTC timestamp of the persisted acknowledgement, or null while revoked.
     */
    readonly ooklaEulaAcceptedAt?: string | null;
    /**
     * MultiSpeed internal review marker recorded with the persisted acknowledgement, or empty when none is stored; this is not an official Ookla document version.
     */
    readonly ooklaEulaVersion?: string;
    /**
     * MultiSpeed internal review marker required by this release for reviewing the current Ookla EULA, Terms of Use, and Privacy Policy; this is not an official Ookla document version.
     */
    readonly ooklaEulaCurrentVersion?: string;
    /**
     * Effective technical-gate state after applying the persisted acknowledgement and environment override.
     */
    readonly ooklaEulaEffectiveAccepted?: boolean;
    /**
     * Source currently opening the technical gate.
     */
    readonly ooklaEulaAcceptanceSource?: 'none' | 'persisted' | 'environment';
};

export type OoklaEulaAcceptanceRequest = {
    /**
     * Legacy-named technical gate value; true records agreement to the current Ookla EULA and Terms of Use and acknowledgement that the Privacy Policy was reviewed.
     */
    accepted: boolean;
    /**
     * Must be true when accepted is true and confirms authorization for MultiSpeed to pass --accept-license and --accept-gdpr non-interactively plus that the personal-computer/non-commercial deployment, device type, and any network access from multiple devices fit current documents or have separate written Ookla authorization; revocation does not require confirmation.
     */
    confirmed: boolean;
};

export type ConfigurationSettings = {
    displayUnits: 'bits' | 'bytes';
    defaultTimezone: string;
    globalConcurrency: number;
    allowSeparateWanConcurrency: boolean;
    retentionMode: 'forever' | 'days' | 'months';
    retentionValue: number;
    defaultChartRange: '24h' | '7d' | '30d' | '90d';
    interfaceRefreshIntervalSeconds: number;
    defaultTaskTimeoutSeconds: number;
    databaseMaintenanceSchedule: string;
};

export type ConfigurationRouteProfile = RouteProfileFields & {
    id: Uuid;
};

export type ConfigurationTask = TaskFields & {
    id: Uuid;
};

export type ConfigurationDocument = {
    format: 'multispeed-config';
    version: 1;
    exportedAt: string;
    applicationVersion: string;
    settings: ConfigurationSettings;
    routeProfiles: Array<ConfigurationRouteProfile>;
    tasks: Array<ConfigurationTask>;
};

export type ConfigurationImportResult = {
    importedAt: string;
    taskCount: number;
    routeProfileCount: number;
    settingsUpdated: boolean;
};

export type RetentionMetrics = {
    mode: 'forever' | 'days' | 'months' | 'manual';
    cutoff?: string;
    startedAt: string;
    finishedAt: string;
    /**
     * Go duration encoded as nanoseconds.
     */
    duration: number;
    batches: number;
    deletedResults: number;
    limitReached: boolean;
    maintenancePerformed: boolean;
};

export type StatisticsGranularity = 'raw' | 'day' | 'iso-week' | 'month' | 'year' | 'custom';

export type StatisticsDimension = '' | 'task' | 'interface' | 'source-ip' | 'provider' | 'server' | 'route-profile' | 'public-ip';

export type StatisticsReport = {
    from: string;
    to: string;
    granularity: StatisticsGranularity;
    reportingTimezone: string;
    groupBy?: StatisticsDimension;
    totalResults: number;
    /**
     * Exact full-range aggregate calculated from all matching raw results, never from averages of buckets.
     */
    overall: StatisticsBucket;
    groups: Array<StatisticsGroup>;
};

export type StatisticsGroup = {
    key: string;
    label: string;
    /**
     * Exact full-range aggregate for this comparison group.
     */
    overall: StatisticsBucket;
    buckets: Array<StatisticsBucket>;
};

export type StatisticsBucket = {
    start: string;
    end: string;
    label: string;
    resultId?: string;
    counts: StatisticsCounts;
    /**
     * Successful results as a percentage of completed results (successful plus failed).
     */
    successRatePercent: number | null;
    /**
     * Failed results as a percentage of completed results (successful plus failed).
     */
    failureRatePercent: number | null;
    metrics: StatisticsMetrics;
};

export type StatisticsCounts = {
    total: number;
    successful: number;
    failed: number;
    skipped: number;
    cancelled: number;
    other: number;
};

export type StatisticsMetrics = {
    downloadBitsPerSecond: MetricSummary;
    uploadBitsPerSecond: MetricSummary;
    latencyMilliseconds: MetricSummary;
    jitterMilliseconds: MetricSummary;
    packetLossPercent: MetricSummary;
    executionDurationMilliseconds: MetricSummary;
};

export type MetricSummary = {
    count: number;
    minimum: number | null;
    maximum: number | null;
    average: number | null;
    median: number | null;
    p95: number | null;
    standardDeviation: number | null;
};

export type SystemInformation = {
    product: 'MultiSpeed';
    version: string;
    gitCommit: string;
    buildTime: string;
    /**
     * Compatibility alias for `buildTime`.
     */
    buildDate: string;
    goVersion: string;
    operatingSystem: 'linux';
    architecture: 'amd64';
    hostname: string;
    databasePath: string;
    databaseSizeBytes: number;
    schemaVersion: number;
    providers: Array<ProviderDescriptor>;
    interfaces: Array<NetworkInterface>;
    interfacesRefreshedAt: string;
    taskCount: number;
    resultCount: number;
    runningTaskCount: number;
    uptimeSeconds: number;
    authenticationEnabled: false;
    internetExposureWarning: string;
};

export type SettingsWritable = {
    displayUnits: 'bits' | 'bytes';
    defaultTimezone: string;
    globalConcurrency: number;
    allowSeparateWanConcurrency: boolean;
    retentionMode: 'forever' | 'days' | 'months';
    retentionValue: number;
    defaultChartRange: '24h' | '7d' | '30d' | '90d';
    interfaceRefreshIntervalSeconds: number;
    defaultTaskTimeoutSeconds: number;
    databaseMaintenanceSchedule: string;
};

export type ResourceId = Uuid;

export type ProviderPath = ProviderId;

export type Page = number;

export type PageSize = number;

export type TaskIdFilter = Uuid;

export type ProviderFilter = ProviderId;

export type StatusFilter = ResultStatus;

export type InterfaceFilter = InterfaceName;

export type SourceIpFilter = IpAddress;

export type ServerIdFilter = string;

/**
 * Inclusive RFC 3339 start instant.
 */
export type FromFilter = string;

/**
 * Exclusive RFC 3339 end instant.
 */
export type ToFilter = string;

export type ResultSort = 'startedAt' | 'finishedAt' | 'download' | 'upload' | 'latency';

export type SortDirection = 'asc' | 'desc';

/**
 * Repeat the parameter or provide comma-separated values.
 */
export type TaskIdListFilter = Array<Uuid>;

/**
 * Repeat the parameter or provide comma-separated values.
 */
export type ProviderListFilter = Array<ProviderId>;

/**
 * Repeat the parameter or provide comma-separated values. The legacy interfaceName alias shares this combined 200-value limit.
 */
export type InterfaceListFilter = Array<InterfaceName>;

/**
 * Repeat the parameter or provide comma-separated values.
 */
export type SourceIpListFilter = Array<IpAddress>;

/**
 * Repeat the parameter or provide comma-separated values.
 */
export type ServerIdListFilter = Array<string>;

/**
 * Repeat the parameter or provide comma-separated values.
 */
export type RouteProfileIdListFilter = Array<Uuid>;

/**
 * Repeat the parameter or provide comma-separated values.
 */
export type PublicIpListFilter = Array<IpAddress>;

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type GetHealthResponses = {
    /**
     * Process is alive.
     */
    200: Health;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type GetReadinessErrors = {
    /**
     * Application startup/integrity dependencies are not ready.
     */
    503: ErrorEnvelope;
};

export type GetReadinessError = GetReadinessErrors[keyof GetReadinessErrors];

export type GetReadinessResponses = {
    /**
     * Database, integrity checks, and migrations are ready.
     */
    200: Readiness;
};

export type GetReadinessResponse = GetReadinessResponses[keyof GetReadinessResponses];

export type ListTasksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tasks';
};

export type ListTasksErrors = {
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type ListTasksError = ListTasksErrors[keyof ListTasksErrors];

export type ListTasksResponses = {
    /**
     * Tasks ordered by name.
     */
    200: Array<Task>;
};

export type ListTasksResponse = ListTasksResponses[keyof ListTasksResponses];

export type CreateTaskData = {
    body: TaskInput;
    path?: never;
    query?: never;
    url: '/tasks';
};

export type CreateTaskErrors = {
    /**
     * Malformed, oversized, multiple-value, or schema-incompatible JSON.
     */
    400: ErrorEnvelope;
    /**
     * A JSON body was sent without Content-Type: application/json.
     */
    415: ErrorEnvelope;
    /**
     * The resource, schedule, target, interface, source address, or route is invalid.
     */
    422: ErrorEnvelope;
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type CreateTaskError = CreateTaskErrors[keyof CreateTaskErrors];

export type CreateTaskResponses = {
    /**
     * Task was persisted and its schedule was installed.
     */
    201: Task;
};

export type CreateTaskResponse = CreateTaskResponses[keyof CreateTaskResponses];

export type ValidateTransientTaskData = {
    body: TaskInput;
    path?: never;
    query?: never;
    url: '/tasks/validate';
};

export type ValidateTransientTaskErrors = {
    /**
     * Malformed, oversized, multiple-value, or schema-incompatible JSON.
     */
    400: ErrorEnvelope;
    /**
     * A JSON body was sent without Content-Type: application/json.
     */
    415: ErrorEnvelope;
    /**
     * The task DTO, provider target, interface/source, route, or public path is invalid.
     */
    422: ErrorEnvelope | RouteValidation;
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type ValidateTransientTaskError = ValidateTransientTaskErrors[keyof ValidateTransientTaskErrors];

export type ValidateTransientTaskResponses = {
    /**
     * The unsaved task and selected network path are valid.
     */
    200: RouteValidation;
};

export type ValidateTransientTaskResponse = ValidateTransientTaskResponses[keyof ValidateTransientTaskResponses];

export type DeleteTaskData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/tasks/{id}';
};

export type DeleteTaskErrors = {
    /**
     * Resource or provider was not found.
     */
    404: ErrorEnvelope;
    /**
     * The operation conflicts with current resource, execution, or queue state.
     */
    409: ErrorEnvelope;
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type DeleteTaskError = DeleteTaskErrors[keyof DeleteTaskErrors];

export type DeleteTaskResponses = {
    /**
     * Task deleted; historical results were preserved.
     */
    204: void;
};

export type DeleteTaskResponse = DeleteTaskResponses[keyof DeleteTaskResponses];

export type GetTaskData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/tasks/{id}';
};

export type GetTaskErrors = {
    /**
     * Resource or provider was not found.
     */
    404: ErrorEnvelope;
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type GetTaskError = GetTaskErrors[keyof GetTaskErrors];

export type GetTaskResponses = {
    /**
     * Task details.
     */
    200: Task;
};

export type GetTaskResponse = GetTaskResponses[keyof GetTaskResponses];

export type UpdateTaskData = {
    body: TaskInput;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/tasks/{id}';
};

export type UpdateTaskErrors = {
    /**
     * Malformed, oversized, multiple-value, or schema-incompatible JSON.
     */
    400: ErrorEnvelope;
    /**
     * Resource or provider was not found.
     */
    404: ErrorEnvelope;
    /**
     * A JSON body was sent without Content-Type: application/json.
     */
    415: ErrorEnvelope;
    /**
     * The resource, schedule, target, interface, source address, or route is invalid.
     */
    422: ErrorEnvelope;
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type UpdateTaskError = UpdateTaskErrors[keyof UpdateTaskErrors];

export type UpdateTaskResponses = {
    /**
     * Updated task.
     */
    200: Task;
};

export type UpdateTaskResponse = UpdateTaskResponses[keyof UpdateTaskResponses];

export type RunTaskData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/tasks/{id}/run';
};

export type RunTaskErrors = {
    /**
     * Resource or provider was not found.
     */
    404: ErrorEnvelope;
    /**
     * The operation conflicts with current resource, execution, or queue state.
     */
    409: ErrorEnvelope;
    /**
     * The operation-specific per-client rate limit was exceeded. Current responses do not include a Retry-After header; clients must observe the documented fixed window.
     */
    429: ErrorEnvelope;
};

export type RunTaskError = RunTaskErrors[keyof RunTaskErrors];

export type RunTaskResponses = {
    /**
     * A queued result was created.
     */
    202: Result;
};

export type RunTaskResponse = RunTaskResponses[keyof RunTaskResponses];

export type ValidateTaskData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/tasks/{id}/validate';
};

export type ValidateTaskErrors = {
    /**
     * Resource or provider was not found.
     */
    404: ErrorEnvelope;
    /**
     * Task or selected route is invalid. The response is either the standard error envelope or a failed route snapshot.
     */
    422: ErrorEnvelope | RouteValidation;
};

export type ValidateTaskError = ValidateTaskErrors[keyof ValidateTaskErrors];

export type ValidateTaskResponses = {
    /**
     * Task and route are valid.
     */
    200: RouteValidation;
};

export type ValidateTaskResponse = ValidateTaskResponses[keyof ValidateTaskResponses];

export type DuplicateTaskData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/tasks/{id}/duplicate';
};

export type DuplicateTaskErrors = {
    /**
     * Resource or provider was not found.
     */
    404: ErrorEnvelope;
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type DuplicateTaskError = DuplicateTaskErrors[keyof DuplicateTaskErrors];

export type DuplicateTaskResponses = {
    /**
     * Disabled copy with a new ID.
     */
    201: Task;
};

export type DuplicateTaskResponse = DuplicateTaskResponses[keyof DuplicateTaskResponses];

export type GetTaskNextRunsData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/tasks/{id}/next-runs';
};

export type GetTaskNextRunsErrors = {
    /**
     * Resource or provider was not found.
     */
    404: ErrorEnvelope;
    /**
     * The resource, schedule, target, interface, source address, or route is invalid.
     */
    422: ErrorEnvelope;
};

export type GetTaskNextRunsError = GetTaskNextRunsErrors[keyof GetTaskNextRunsErrors];

export type GetTaskNextRunsResponses = {
    /**
     * Next runs in UTC for the task's IANA timezone.
     */
    200: NextRuns;
};

export type GetTaskNextRunsResponse = GetTaskNextRunsResponses[keyof GetTaskNextRunsResponses];

export type ListResultsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        taskId?: Uuid;
        provider?: ProviderId;
        status?: ResultStatus;
        interface?: InterfaceName;
        sourceIp?: IpAddress;
        serverId?: string;
        /**
         * Inclusive RFC 3339 start instant.
         */
        from?: string;
        /**
         * Exclusive RFC 3339 end instant.
         */
        to?: string;
        sort?: 'startedAt' | 'finishedAt' | 'download' | 'upload' | 'latency';
        direction?: 'asc' | 'desc';
    };
    url: '/results';
};

export type ListResultsErrors = {
    /**
     * One or more query parameters are invalid.
     */
    400: ErrorEnvelope;
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type ListResultsError = ListResultsErrors[keyof ListResultsErrors];

export type ListResultsResponses = {
    /**
     * Paginated result set.
     */
    200: ResultPage;
};

export type ListResultsResponse = ListResultsResponses[keyof ListResultsResponses];

export type GetDashboardResultSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/results/dashboard-summary';
};

export type GetDashboardResultSummaryErrors = {
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type GetDashboardResultSummaryError = GetDashboardResultSummaryErrors[keyof GetDashboardResultSummaryErrors];

export type GetDashboardResultSummaryResponses = {
    /**
     * Bounded dashboard result snapshot.
     */
    200: DashboardResultSummary;
};

export type GetDashboardResultSummaryResponse = GetDashboardResultSummaryResponses[keyof GetDashboardResultSummaryResponses];

export type DeleteResultData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/results/{id}';
};

export type DeleteResultErrors = {
    /**
     * Resource or provider was not found.
     */
    404: ErrorEnvelope;
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type DeleteResultError = DeleteResultErrors[keyof DeleteResultErrors];

export type DeleteResultResponses = {
    /**
     * Result deleted.
     */
    204: void;
};

export type DeleteResultResponse = DeleteResultResponses[keyof DeleteResultResponses];

export type GetResultData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/results/{id}';
};

export type GetResultErrors = {
    /**
     * Resource or provider was not found.
     */
    404: ErrorEnvelope;
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type GetResultError = GetResultErrors[keyof GetResultErrors];

export type GetResultResponses = {
    /**
     * Result details.
     */
    200: Result;
};

export type GetResultResponse = GetResultResponses[keyof GetResultResponses];

export type DeleteResultsBatchData = {
    body: {
        ids: Array<Uuid>;
    };
    path?: never;
    query?: never;
    url: '/results/delete-batch';
};

export type DeleteResultsBatchErrors = {
    /**
     * Malformed, oversized, multiple-value, or schema-incompatible JSON.
     */
    400: ErrorEnvelope;
    /**
     * A JSON body was sent without Content-Type: application/json.
     */
    415: ErrorEnvelope;
};

export type DeleteResultsBatchError = DeleteResultsBatchErrors[keyof DeleteResultsBatchErrors];

export type DeleteResultsBatchResponses = {
    /**
     * Number of matching rows deleted.
     */
    200: {
        deleted: number;
    };
};

export type DeleteResultsBatchResponse = DeleteResultsBatchResponses[keyof DeleteResultsBatchResponses];

export type GetStatisticsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Inclusive start. Defaults to 30 days before the request.
         */
        from?: string;
        /**
         * Exclusive end. Defaults to the request time. Ranges are limited to ten years.
         */
        to?: string;
        granularity?: StatisticsGranularity;
        /**
         * IANA reporting timezone; defaults to persisted settings.
         */
        timezone?: string;
        groupBy?: StatisticsDimension;
        /**
         * Repeat the parameter or provide comma-separated values.
         */
        taskId?: Array<Uuid>;
        /**
         * Repeat the parameter or provide comma-separated values.
         */
        provider?: Array<ProviderId>;
        /**
         * Repeat the parameter or provide comma-separated values. The legacy interfaceName alias shares this combined 200-value limit.
         */
        interface?: Array<InterfaceName>;
        /**
         * Repeat the parameter or provide comma-separated values.
         */
        sourceIp?: Array<IpAddress>;
        /**
         * Repeat the parameter or provide comma-separated values.
         */
        serverId?: Array<string>;
        /**
         * Repeat the parameter or provide comma-separated values.
         */
        routeProfileId?: Array<Uuid>;
        /**
         * Repeat the parameter or provide comma-separated values.
         */
        publicIp?: Array<IpAddress>;
    };
    url: '/statistics';
};

export type GetStatisticsErrors = {
    /**
     * One or more query parameters are invalid.
     */
    400: ErrorEnvelope;
    /**
     * The statistics query matched more than 50,000 results, would materialize more than 5,000 output points or 1,000 comparison groups, or contains a comparison-dimension value longer than 512 bytes.
     */
    413: ErrorEnvelope;
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type GetStatisticsError = GetStatisticsErrors[keyof GetStatisticsErrors];

export type GetStatisticsResponses = {
    /**
     * Normalized statistics report. Raw queries are limited to 90 days; the materialized report contains at most 5,000 output points and 1,000 comparison groups.
     */
    200: StatisticsReport;
};

export type GetStatisticsResponse = GetStatisticsResponses[keyof GetStatisticsResponses];

export type ListInterfacesData = {
    body?: never;
    path?: never;
    query?: {
        includeLoopback?: boolean;
        includeDown?: boolean;
        includeVirtual?: boolean;
    };
    url: '/interfaces';
};

export type ListInterfacesErrors = {
    /**
     * One or more query parameters are invalid.
     */
    400: ErrorEnvelope;
};

export type ListInterfacesError = ListInterfacesErrors[keyof ListInterfacesErrors];

export type ListInterfacesResponses = {
    /**
     * Interface snapshot from the active Linux network namespace.
     */
    200: InterfaceSnapshot;
};

export type ListInterfacesResponse = ListInterfacesResponses[keyof ListInterfacesResponses];

export type RefreshInterfacesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/interfaces/refresh';
};

export type RefreshInterfacesErrors = {
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type RefreshInterfacesError = RefreshInterfacesErrors[keyof RefreshInterfacesErrors];

export type RefreshInterfacesResponses = {
    /**
     * Refreshed interface snapshot.
     */
    200: InterfaceSnapshot;
};

export type RefreshInterfacesResponse = RefreshInterfacesResponses[keyof RefreshInterfacesResponses];

export type ListRouteProfilesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/route-profiles';
};

export type ListRouteProfilesErrors = {
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type ListRouteProfilesError = ListRouteProfilesErrors[keyof ListRouteProfilesErrors];

export type ListRouteProfilesResponses = {
    /**
     * Route profiles.
     */
    200: Array<RouteProfile>;
};

export type ListRouteProfilesResponse = ListRouteProfilesResponses[keyof ListRouteProfilesResponses];

export type CreateRouteProfileData = {
    body: RouteProfileInput;
    path?: never;
    query?: never;
    url: '/route-profiles';
};

export type CreateRouteProfileErrors = {
    /**
     * Malformed, oversized, multiple-value, or schema-incompatible JSON.
     */
    400: ErrorEnvelope;
    /**
     * A JSON body was sent without Content-Type: application/json.
     */
    415: ErrorEnvelope;
    /**
     * The resource, schedule, target, interface, source address, or route is invalid.
     */
    422: ErrorEnvelope;
};

export type CreateRouteProfileError = CreateRouteProfileErrors[keyof CreateRouteProfileErrors];

export type CreateRouteProfileResponses = {
    /**
     * Created profile.
     */
    201: RouteProfile;
};

export type CreateRouteProfileResponse = CreateRouteProfileResponses[keyof CreateRouteProfileResponses];

export type DeleteRouteProfileData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/route-profiles/{id}';
};

export type DeleteRouteProfileErrors = {
    /**
     * Resource or provider was not found.
     */
    404: ErrorEnvelope;
    /**
     * The operation conflicts with current resource, execution, or queue state.
     */
    409: ErrorEnvelope;
};

export type DeleteRouteProfileError = DeleteRouteProfileErrors[keyof DeleteRouteProfileErrors];

export type DeleteRouteProfileResponses = {
    /**
     * Profile deleted.
     */
    204: void;
};

export type DeleteRouteProfileResponse = DeleteRouteProfileResponses[keyof DeleteRouteProfileResponses];

export type GetRouteProfileData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/route-profiles/{id}';
};

export type GetRouteProfileErrors = {
    /**
     * Resource or provider was not found.
     */
    404: ErrorEnvelope;
};

export type GetRouteProfileError = GetRouteProfileErrors[keyof GetRouteProfileErrors];

export type GetRouteProfileResponses = {
    /**
     * Route profile.
     */
    200: RouteProfile;
};

export type GetRouteProfileResponse = GetRouteProfileResponses[keyof GetRouteProfileResponses];

export type UpdateRouteProfileData = {
    body: RouteProfileInput;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/route-profiles/{id}';
};

export type UpdateRouteProfileErrors = {
    /**
     * Malformed, oversized, multiple-value, or schema-incompatible JSON.
     */
    400: ErrorEnvelope;
    /**
     * Resource or provider was not found.
     */
    404: ErrorEnvelope;
    /**
     * A JSON body was sent without Content-Type: application/json.
     */
    415: ErrorEnvelope;
    /**
     * The resource, schedule, target, interface, source address, or route is invalid.
     */
    422: ErrorEnvelope;
};

export type UpdateRouteProfileError = UpdateRouteProfileErrors[keyof UpdateRouteProfileErrors];

export type UpdateRouteProfileResponses = {
    /**
     * Updated profile.
     */
    200: RouteProfile;
};

export type UpdateRouteProfileResponse = UpdateRouteProfileResponses[keyof UpdateRouteProfileResponses];

export type ValidateRouteProfileData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/route-profiles/{id}/validate';
};

export type ValidateRouteProfileErrors = {
    /**
     * Resource or provider was not found.
     */
    404: ErrorEnvelope;
    /**
     * Validation completed with a mismatch or reachability failure.
     */
    422: RouteValidation;
};

export type ValidateRouteProfileError = ValidateRouteProfileErrors[keyof ValidateRouteProfileErrors];

export type ValidateRouteProfileResponses = {
    /**
     * Route matched the profile.
     */
    200: RouteValidation;
};

export type ValidateRouteProfileResponse = ValidateRouteProfileResponses[keyof ValidateRouteProfileResponses];

export type ListProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/providers';
};

export type ListProvidersResponses = {
    /**
     * Provider descriptors.
     */
    200: Array<ProviderDescriptor>;
};

export type ListProvidersResponse = ListProvidersResponses[keyof ListProvidersResponses];

export type GetOoklaBinaryStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/providers/ookla/binary';
};

export type GetOoklaBinaryStatusResponses = {
    /**
     * Deployment-owned upload capability and installation state.
     */
    200: OoklaBinaryStatus;
};

export type GetOoklaBinaryStatusResponse = GetOoklaBinaryStatusResponses[keyof GetOoklaBinaryStatusResponses];

export type UploadOoklaBinaryData = {
    body: Blob | File;
    path?: never;
    query?: never;
    url: '/providers/ookla/binary';
};

export type UploadOoklaBinaryErrors = {
    /**
     * Managed executable upload is not enabled by deployment policy.
     */
    403: ErrorEnvelope;
    /**
     * The managed executable target is a directory, symbolic link, or otherwise conflicts with the required regular-file path.
     */
    409: ErrorEnvelope;
    /**
     * The executable exceeds the 64 MiB upload limit.
     */
    413: ErrorEnvelope;
    /**
     * A JSON body was sent without Content-Type: application/json.
     */
    415: ErrorEnvelope;
    /**
     * The resource, schedule, target, interface, source address, or route is invalid.
     */
    422: ErrorEnvelope;
    /**
     * The operation-specific per-client rate limit was exceeded. Current responses do not include a Retry-After header; clients must observe the documented fixed window.
     */
    429: ErrorEnvelope;
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type UploadOoklaBinaryError = UploadOoklaBinaryErrors[keyof UploadOoklaBinaryErrors];

export type UploadOoklaBinaryResponses = {
    /**
     * The validated executable was installed in managed persistent storage.
     */
    201: OoklaBinaryInstallResult;
};

export type UploadOoklaBinaryResponse = UploadOoklaBinaryResponses[keyof UploadOoklaBinaryResponses];

export type ListProviderServersData = {
    body?: never;
    path: {
        provider: ProviderId;
    };
    query: {
        interface: InterfaceName;
        sourceIp: IpAddress;
        ipFamily?: IpFamily;
        search?: string;
        limit?: number;
    };
    url: '/providers/{provider}/servers';
};

export type ListProviderServersErrors = {
    /**
     * Resource or provider was not found.
     */
    404: ErrorEnvelope;
    /**
     * The resource, schedule, target, interface, source address, or route is invalid.
     */
    422: ErrorEnvelope;
    /**
     * The operation-specific per-client rate limit was exceeded. Current responses do not include a Retry-After header; clients must observe the documented fixed window.
     */
    429: ErrorEnvelope;
    /**
     * A bounded provider operation failed.
     */
    502: ErrorEnvelope;
};

export type ListProviderServersError = ListProviderServersErrors[keyof ListProviderServersErrors];

export type ListProviderServersResponses = {
    /**
     * Matching provider servers.
     */
    200: Array<ProviderServer>;
};

export type ListProviderServersResponse = ListProviderServersResponses[keyof ListProviderServersResponses];

export type ValidateProviderServerData = {
    body: ProviderServerValidation;
    path: {
        provider: ProviderId;
    };
    query?: never;
    url: '/providers/{provider}/validate-server';
};

export type ValidateProviderServerErrors = {
    /**
     * Malformed, oversized, multiple-value, or schema-incompatible JSON.
     */
    400: ErrorEnvelope;
    /**
     * Resource or provider was not found.
     */
    404: ErrorEnvelope;
    /**
     * A JSON body was sent without Content-Type: application/json.
     */
    415: ErrorEnvelope;
    /**
     * The resource, schedule, target, interface, source address, or route is invalid.
     */
    422: ErrorEnvelope;
    /**
     * The operation-specific per-client rate limit was exceeded. Current responses do not include a Retry-After header; clients must observe the documented fixed window.
     */
    429: ErrorEnvelope;
};

export type ValidateProviderServerError = ValidateProviderServerErrors[keyof ValidateProviderServerErrors];

export type ValidateProviderServerResponses = {
    /**
     * The target, route, and bounded provider reachability checks succeeded.
     */
    200: {
        valid: true;
        success: true;
        message: string;
        provider: ProviderId;
        target: TestTarget;
    };
};

export type ValidateProviderServerResponse = ValidateProviderServerResponses[keyof ValidateProviderServerResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings';
};

export type GetSettingsErrors = {
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type GetSettingsError = GetSettingsErrors[keyof GetSettingsErrors];

export type GetSettingsResponses = {
    /**
     * Current settings.
     */
    200: Settings;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type UpdateSettingsData = {
    body: SettingsWritable;
    path?: never;
    query?: never;
    url: '/settings';
};

export type UpdateSettingsErrors = {
    /**
     * Malformed, oversized, multiple-value, or schema-incompatible JSON.
     */
    400: ErrorEnvelope;
    /**
     * A JSON body was sent without Content-Type: application/json.
     */
    415: ErrorEnvelope;
    /**
     * The resource, schedule, target, interface, source address, or route is invalid.
     */
    422: ErrorEnvelope;
};

export type UpdateSettingsError = UpdateSettingsErrors[keyof UpdateSettingsErrors];

export type UpdateSettingsResponses = {
    /**
     * Updated settings.
     */
    200: Settings;
};

export type UpdateSettingsResponse = UpdateSettingsResponses[keyof UpdateSettingsResponses];

export type UpdateOoklaEulaAcceptanceData = {
    body: OoklaEulaAcceptanceRequest;
    path?: never;
    query?: never;
    url: '/settings/ookla-eula';
};

export type UpdateOoklaEulaAcceptanceErrors = {
    /**
     * Malformed, oversized, multiple-value, or schema-incompatible JSON.
     */
    400: ErrorEnvelope;
    /**
     * A JSON body was sent without Content-Type: application/json.
     */
    415: ErrorEnvelope;
    /**
     * The resource, schedule, target, interface, source address, or route is invalid.
     */
    422: ErrorEnvelope;
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type UpdateOoklaEulaAcceptanceError = UpdateOoklaEulaAcceptanceErrors[keyof UpdateOoklaEulaAcceptanceErrors];

export type UpdateOoklaEulaAcceptanceResponses = {
    /**
     * Updated settings and persisted acknowledgement timestamp.
     */
    200: Settings;
};

export type UpdateOoklaEulaAcceptanceResponse = UpdateOoklaEulaAcceptanceResponses[keyof UpdateOoklaEulaAcceptanceResponses];

export type CleanupResultsData = {
    body?: {
        /**
         * Delete results strictly older than this past UTC instant.
         */
        before?: string;
    };
    path?: never;
    query?: never;
    url: '/retention/cleanup';
};

export type CleanupResultsErrors = {
    /**
     * Malformed, oversized, multiple-value, or schema-incompatible JSON.
     */
    400: ErrorEnvelope;
    /**
     * A JSON body was sent without Content-Type: application/json.
     */
    415: ErrorEnvelope;
    /**
     * The resource, schedule, target, interface, source address, or route is invalid.
     */
    422: ErrorEnvelope;
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type CleanupResultsError = CleanupResultsErrors[keyof CleanupResultsErrors];

export type CleanupResultsResponses = {
    /**
     * Cleanup metrics, including whether the safety batch limit was reached.
     */
    200: RetentionMetrics;
};

export type CleanupResultsResponse = CleanupResultsResponses[keyof CleanupResultsResponses];

export type ExportResultsCsvData = {
    body?: never;
    path?: never;
    query?: {
        taskId?: Uuid;
        provider?: ProviderId;
        status?: ResultStatus;
        interface?: InterfaceName;
        sourceIp?: IpAddress;
        serverId?: string;
        /**
         * Inclusive RFC 3339 start instant.
         */
        from?: string;
        /**
         * Exclusive RFC 3339 end instant.
         */
        to?: string;
        sort?: 'startedAt' | 'finishedAt' | 'download' | 'upload' | 'latency';
        direction?: 'asc' | 'desc';
    };
    url: '/exports/results.csv';
};

export type ExportResultsCsvErrors = {
    /**
     * One or more query parameters are invalid.
     */
    400: ErrorEnvelope;
};

export type ExportResultsCsvError = ExportResultsCsvErrors[keyof ExportResultsCsvErrors];

export type ExportResultsCsvResponses = {
    /**
     * UTF-8 CSV attachment.
     */
    200: string;
};

export type ExportResultsCsvResponse = ExportResultsCsvResponses[keyof ExportResultsCsvResponses];

export type ExportResultsJsonData = {
    body?: never;
    path?: never;
    query?: {
        taskId?: Uuid;
        provider?: ProviderId;
        status?: ResultStatus;
        interface?: InterfaceName;
        sourceIp?: IpAddress;
        serverId?: string;
        /**
         * Inclusive RFC 3339 start instant.
         */
        from?: string;
        /**
         * Exclusive RFC 3339 end instant.
         */
        to?: string;
        sort?: 'startedAt' | 'finishedAt' | 'download' | 'upload' | 'latency';
        direction?: 'asc' | 'desc';
    };
    url: '/exports/results.json';
};

export type ExportResultsJsonErrors = {
    /**
     * One or more query parameters are invalid.
     */
    400: ErrorEnvelope;
};

export type ExportResultsJsonError = ExportResultsJsonErrors[keyof ExportResultsJsonErrors];

export type ExportResultsJsonResponses = {
    /**
     * JSON array attachment.
     */
    200: Array<Result>;
};

export type ExportResultsJsonResponse = ExportResultsJsonResponses[keyof ExportResultsJsonResponses];

export type ExportConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/config/export';
};

export type ExportConfigurationErrors = {
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type ExportConfigurationError = ExportConfigurationErrors[keyof ExportConfigurationErrors];

export type ExportConfigurationResponses = {
    /**
     * Versioned JSON configuration attachment from one consistent database snapshot.
     */
    200: ConfigurationDocument;
};

export type ExportConfigurationResponse = ExportConfigurationResponses[keyof ExportConfigurationResponses];

export type ImportConfigurationData = {
    body: ConfigurationDocument;
    path?: never;
    query?: never;
    url: '/config/import';
};

export type ImportConfigurationErrors = {
    /**
     * Malformed, oversized, multiple-value, or schema-incompatible JSON.
     */
    400: ErrorEnvelope;
    /**
     * The operation conflicts with current resource, execution, or queue state.
     */
    409: ErrorEnvelope;
    /**
     * A JSON body was sent without Content-Type: application/json.
     */
    415: ErrorEnvelope;
    /**
     * The resource, schedule, target, interface, source address, or route is invalid.
     */
    422: ErrorEnvelope;
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type ImportConfigurationError = ImportConfigurationErrors[keyof ImportConfigurationErrors];

export type ImportConfigurationResponses = {
    /**
     * Configuration imported and schedules reconciled.
     */
    200: ConfigurationImportResult;
};

export type ImportConfigurationResponse = ImportConfigurationResponses[keyof ImportConfigurationResponses];

export type CreateBackupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/backup';
};

export type CreateBackupErrors = {
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type CreateBackupError = CreateBackupErrors[keyof CreateBackupErrors];

export type CreateBackupResponses = {
    /**
     * Complete SQLite database snapshot.
     */
    200: Blob | File;
};

export type CreateBackupResponse = CreateBackupResponses[keyof CreateBackupResponses];

export type StreamEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/events';
};

export type StreamEventsErrors = {
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
    /**
     * The bounded live-event subscriber capacity has been reached.
     */
    503: ErrorEnvelope;
};

export type StreamEventsError = StreamEventsErrors[keyof StreamEventsErrors];

export type StreamEventsResponses = {
    /**
     * Server-Sent Event stream with heartbeat comments.
     */
    200: string;
};

export type StreamEventsResponse = StreamEventsResponses[keyof StreamEventsResponses];

export type GetSystemInformationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system';
};

export type GetSystemInformationErrors = {
    /**
     * Sanitized internal error.
     */
    500: ErrorEnvelope;
};

export type GetSystemInformationError = GetSystemInformationErrors[keyof GetSystemInformationErrors];

export type GetSystemInformationResponses = {
    /**
     * System information without environment-variable values.
     */
    200: SystemInformation;
};

export type GetSystemInformationResponse = GetSystemInformationResponses[keyof GetSystemInformationResponses];
